### PR TITLE
update for new Prog8 4.4 release

### PR DESCRIPTION
**Pull request by irmen**
Hi, another small update, a bit unexpectedly.
However the just released 4.4 version of Prog8 has some slight library and syntax changes so I've updated the code to reflect those.

More interesting though, is that I managed to improve the code generation again and now Prog8 4.4 is actually a bit _faster_ than optimized cc65 in two of the benchmarks.  It would be great if you can re-run them and update the tables with the new results :chart_with_upwards_trend: 

I added some output to the sieve benchmark as well so I could visually confirm it still computes the primes correctly. Maybe something you might consider doing in the other versions of this benchmark as well?

The code generation for the plasma benchmark inner loop still isn't optimal but I discovered a nasty bottleneck that is now easily avoided by a small temporary variable change in the code.

Thanks again !

### CODE REVIEW

**Comment by KarolS** [comment]
Thanks, I'm on it.

**Comment by irmen** [comment]
I think you have a copy-paste error for the prog8 results on the sieve tests? It should be ~890 while it still shows the older value I think.   Otherwise, thanks for merging!

**Comment by KarolS** [comment]
Oops, sorry, I pasted the Prog8 result in the KickC row (it's less than 890 because I removed the extra output that is absent in all other versions and unnecessarily slows the Prog8 version down).

As an apology, I offer finally adding Prog8 to the bar charts, as it's now fast enough that it won't stretch the scale too much. What colour do you want Prog8 to be represented with?

**Comment by irmen** [comment]
Purple would be my choice :paintbrush: 
Thanks Karol!

I know it's just a few micro benchmarks but I honestly didn't expect to be able to beat cc65... although I still have some work to do for the inner loops of plasma :smile_cat:

**Pull request merged**
